######################################################################
# Automatically generated by qmake (3.1) Sun May 14 21:05:51 2017
######################################################################

TEMPLATE = app
TARGET = chat
INCLUDEPATH += .

# Input
SOURCES += chat.cpp
QT += widgets
